apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres

spec:
replicas: 1
selector:
  matchLabels:
    app: postgres
strategy:
  type: recreate
template:
  metadata:
    labels:
      app: postgres
  spec:
    containers:
      - name: postgres
        image: postgres:latest
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets

        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: postgres-pvc
            path: var/lib/postgres
          - name: postgres-initdb
            mountPath: /docker-entrypoint-initdb.d
    volumes:
      - name: postgres-pvc
        persistentVolumeClaim:
          - claimName: postgres-pvc
      - name: postgres-initdb
