apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    run: redis
spec:
  containers:
    - name: redis
      image: redis:7.2.5-alpine
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
