apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mtail-web-rs
  labels:
    app: mtail-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mtail-web
  template:
    metadata:
      labels:
        app: mtail-web
    spec:
      containers:
        - name: mtail-web
          image: rghost/sharcst_mtail_web:latest
      imagePullSecrets:
        - name: regcred
