apiVersion: v1
kind: Service
metadata:
  name: mtail-service
  labels:
    app: mtail-web
    tier: backend

spec:
  selector:
    app: mtail-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
