apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtail-web
  labels:
    app: mtail-web
    tier: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: mtail-web
  template:
    metadata:
      labels:
        app: mtail-web
        tier: backend
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres 5432; do echo waiting...; sleep 2; done",
            ]
        - name: init-app
          image: busybox:1.28
          command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
      containers:
        - name: mtail-web
          image: rghost/sharcst_mtail_web:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          imagePullSecrets:
            - name: regcred
          ports:
            - containerPort: 8080
