apiVersion: v1
kind: Pod
metadata:
  name: mtail-web
  labels:
    run: mtail-web
spec:
  containers:
    - name: mtail-web
      image: rghost/sharcst_mtail_web:latest
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
  imagePullSecrets:
    - name: regcred
  dnsPolicy: ClusterFirst
  restartPolicy: Always
