
version: '3'
services:
  db:
    image: postgres:latest
    ports:
    - 54321:54321
    volumes:
    - postgres-data:/var/lib/postgresql/data
    env_file:
    - .env

  web:
    build: ./
    ports:
    - 3000:3000
    depends_on:
    - db
    - redis
    env_file:
    - .env

  redis:
    image: redis:6.2.13
    ports:
    - 6379:6379
    volumes:
    - redis_data:/data
    env_file:
    - .env

  minio:
    image: minio/minio
    command: server --console-address ":38821" /data
    container_name: minio_s3_next
    ports:
      - 9000:9000
      - 38821:38821
    env_file:
    - .env
    volumes:
      - s3_minio_data:/data

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch

    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards

    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200","https://opensearch:9200"]'
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin

    networks:
      - opensearch-net


volumes:
  postgres-data:
  opensearch:
  s3_minio_data:
  redis_data:

networks:
  opensearch-net:
