
version: '3'
services:

  nginx:
    image: nginx:1.14.2-alpine
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - nginx_network

  db:
    image: postgres:latest
    ports:
    - 54321:54321
    volumes:
    - postgres-data:/var/lib/postgresql/data
    env_file:
    - .env

  redis:
    image: redis:6.2.13
    ports:
    - 6379:6379
    volumes:
    - redis_data:/data
    env_file:
    - .env

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
    - .env
    volumes:
      - minio_data:/data

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch

    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards

    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200","https://opensearch:9200"]'
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin

    networks:
      - opensearch-net


  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  rabbitmq:
    image: rabbitmq:3.9.29-alpine
    env_file:
    - .env
    ports:
      - 5671:5671
      - 15692:15692
    volumes:
    - rabbitmq:/var/lib/rabbitmq


volumes:
  postgres-data:
  opensearch:
  minio_data:
  redis_data:
  rabbitmq:

networks:
  opensearch-net:
  nginx_network:
    external: true
