# cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - curl
  - python3
  - python3-pip

runcmd:
  - snap install microk8s --classic
  - usermod -aG docker ubuntu
  - usermod -aG microk8s ubuntu
  - chown -f -R ubuntu ~/.kube
  - microk8s status --wait-ready
  - microk8s enable dns ingress
  - echo 'Microk8s installed successfully'
