default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sm_development
  username: postgres
  password: root
  host: localhost
  port: 5432
  url: <%= ENV['DB_URL'] %>

test:
  <<: *default
  database: sm_test
  username: postgres
  password: root
  host: localhost
  port: 5432
  url: <%= ENV['DB_TEST_URL'] %>

production:
  <<: *default
  database: sm_production
  username: <%= ENV['SM_DATABASE_USER'] %>
  password: <%= ENV['SM_DATABASE_PASSWORD'] %>
