test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

minio:
  service: S3
  access_key_id: <%= ENV["MINIO_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["MINIO_SECRET_KEY"] %>
  region: us-east-1
  bucket: <%= ENV["MINIO_BUCKET"] %>
  endpoint: "http://127.0.0.1:9000"
  force_path_style: true

amazon:
  service: S3
  access_key_id: <%= ENV["AWS_SECRET_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  region: eu-north-1
  bucket: <%= ENV["AWS_BUCKET"] %>
