apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: opensearch
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opensearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/sharcst-mtail-opensearch-net: "true"
        io.kompose.service: opensearch
    spec:
      containers:
        - env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
          image: opensearchproject/opensearch:latest
          name: opensearch
          ports:
            - containerPort: 9200
              hostPort: 9200
              protocol: TCP
            - containerPort: 9600
              hostPort: 9600
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: opensearch
      restartPolicy: Always
      volumes:
        - name: opensearch
          persistentVolumeClaim:
            claimName: opensearch
status: {}
