apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: "2023-12-21T21:26:50.52Z"
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: "2023-12-21T21:26:50.52Z"
      labels:
        io.kompose.network/sharcst-mtail-default: "true"
        io.kompose.service: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.13
          restartPolicy: Always
          env:
            - name: REDIS_DEV_CACHE_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_DEV_CACHE_URL
                  name: sharcst-mtail--env
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: sharcst-mtail--env
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: sharcst-mtail--env
            - name: REDIS_PROD_CACHE_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PROD_CACHE_URL
                  name: sharcst-mtail--env
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: sharcst-mtail--env
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
              limits:
                memory: 256Mi
          volumeMounts:
          - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
