- name: Install NGINX
  hosts: production
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Installation Checkup
      service:
        name: nginx
        state: started
        enabled: yes
