apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: "2023-12-21T21:26:50.52Z"
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
    - name: "54321"
      port: 54321
      targetPort: 54321
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
