apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: "2023-12-21T21:26:50.52Z"
  labels:
    io.kompose.service: mailcatcher
  name: mailcatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailcatcher
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: "2023-12-21T21:26:50.52Z"
      labels:
        io.kompose.network/sharcst-mtail-default: "true"
        io.kompose.service: mailcatcher
    spec:
      containers:
        - image: schickling/mailcatcher
          name: mailcatcher
          ports:
            - containerPort: 1080
              hostPort: 1080
              protocol: TCP
              resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "512"
                cpu: "500m"
      restartPolicy: Always
status: {}
