apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2023-12-21T21:26:50.52Z"
  labels:
    io.kompose.service: minio-data
  name: minio-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
